# Generated by Django 3.2.8 on 2022-12-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_auto_20221127_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user_id',
            new_name='user',
        ),
    ]
