# Generated by Django 3.2.8 on 2022-12-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_rename_user_id_business_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={},
        ),
    ]
